name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: installing python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: Installing all our dependencies
        run: pip install numpy tensorflow flask pytest pytest-cov
      - name: Test with pytest
        run: pytest test_regression_project.py --doctest-modules --junitxml=junit/test-results-${{ github.run_number }}.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ github.run_number }}
          path: |
                junit/test-results-${{ github.run_number }}.xml
                htmlcov/*.html                
                htmlcov/*.js                
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID}}
          service_account_key: ${{ secrets.GCP_SA_KEY}}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-app:latest
          build-args: |
            HTTP_PORT=5000
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-app:latest
          service: python-app
          region: us-central1
          platform: managed
          allow-unauthenticated: true
          env_vars: |
            FOO=bar
            ZIP=zap
