on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Build project (if necessary)
      run: python setup.py build
      
    - name: Store build logs
      run: echo "Build logs" > build.log

    - name: Run tests
      run: pytest

    - name: Run tests with coverage
      run: |
        pytest --cov=my_module --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

    - name: Store test results
      run: pytest --junitxml=test_results.xml

    - name: Set up AWS CLI
      run: pip install awscli

    - name: Package code for Lambda
      run: |
        pip install -r requirements.txt -t ./package
        cp -r ./* ./package/
        cd package
        zip -r ../my-function.zip .

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name my-function \
          --zip-file fileb://my-function.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1' # or your preferred region
