name: Python CI/CD Workflow to Google Cloud Run

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build project
      run: python setup.py build > build.log

    - name: Archive build logs
      uses: actions/upload-artifact@v2
      with:
        name: build-logs
        path: build.log

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Generate code coverage report
      run: pytest --cov=./ --cov-report=xml

    - name: Archive test results
      run: pytest --junitxml=test_results.xml

    - name: Archive code coverage report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: coverage.xml

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy PYTHON_REGRESSION_SERVICE --image gcr.io/python-regression-cicd-flow/PYTHON_REGRESSION_SERVICE_IMAGE --region us-central1 --platform managed

