name: Python CI/CD Workflow

on: [push]
env:
  AWS_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project
        run: python setup.py build

      - name: Save build logs
        run: echo "Build logs" > build.log

      - name: Archive build logs
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: build.log

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Generate test coverage report
        run: pytest --cov=./ --cov-report=xml

      - name: Archive test results
        run: pytest --junitxml=test_results.xml

      - name: Archive code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage.xml

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install AWS CLI
        run: pip install awscli

      - name: Prepare Lambda package
        run: |
          pip install -r requirements.txt -t ./package
          rsync -av --progress ./ ./package/ --exclude package
          cd package
          zip -r ../my-function.zip .

      - name: Upload Lambda package to S3 using AWS Actions
        uses: aws-actions/amazon-s3-cp@v1
        with:
          source: ./my-function.zip
          destination: s3://teamboys/my-function.zip
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Update AWS Lambda with package from S3 using AWS Actions
        uses: aws-actions/aws-cli@v1
        with:
          script: |
            aws lambda update-function-code --function-name teamboys-python-app --s3-bucket teamboys --s3-key my-function.zip
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
